<?php
define('PERFECT_SCROLLBAR_DEFAULT_VERSION', '0.6.16');
define('PERFECT_SCROLLBAR_CDN_URL', 'https://cdnjs.cloudflare.com/ajax/libs/jquery.perfect-scrollbar');

/**
 * @file
 * Perfect Srollbar integration implementation.
 */


/**
 * Implements hook_help().
 */
function perfect_scrollbar_help($path, $arg) {
  switch ($path) {
    // Help for the Perfect Scrollbar module.
    case 'admin/help#perfect_scrollbar':
      $output = '<p>' . t('The Perfect Scrollbar helps content managers, authors to add scroll to their content easily');
      $output .= t('For configuration options see the perfect scrollbar <a href="@config">options & settings page</a>.', array('@config' => url('admin/config/user-interface/perfect_scrollbar'))) . '</p>';
      return $output;
  }
}

/**
 * Implements hook_menu().
 */
function perfect_scrollbar_menu() {
  $items['admin/config/user-interface/perfect_scrollbar'] = array(
    'title' => 'Perfect Scrollbar',
    'description' => 'Perfect Scrollbar configuration in Drupal.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('perfect_scrollbar_configurations'),
    'access arguments' => array('administer perfect scrollbar'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'perfect_scrollbar.admin.inc'
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function perfect_scrollbar_permission() {
  return array(
    'administer perfect scrollbar' => array(
      'title' => t('Administer Perfect scrollbar Options & Settings'),
      'description' => t('Allows a user to configure and apply perfect Scrollbar to content.'),
    ),
  );
}

/*
 *
 *
 */
function perfect_scrollbar_init() {
  if(variable_get('perfect_scrollbar')) {
    drupal_add_library('perfect_scrollbar', 'perfect_scrollbar');
    drupal_add_js(drupal_get_path('module', 'perfect_scrollbar') .'/js/add_perfect_scrollbar.js', 'file');

    //Get scrollbar settings
    _set_perfect_scrollbar_settings();
  }
}

/**
 * Implements hook_library().
 */
function perfect_scrollbar_library() {
  $libraries = array();
  $library_path = libraries_get_path('perfect_scrollbar');
  $version = variable_get('perfect_scrollbar_version', PERFECT_SCROLLBAR_DEFAULT_VERSION);
  $compression = variable_get('perfect_scrollbar_compression_type', 'min');
  $cdn = (TRUE == variable_get('perfect_scrollbar_cdn', '0'));

  // Get extension
  $js_extension = (FALSE === empty($compression)) ? $compression . '.js' : 'js';
  $css_extension = (FALSE === empty($compression)) ? $compression . '.css' : 'css';
  $path = (FALSE == $cdn) ? $library_path : PERFECT_SCROLLBAR_CDN_URL . '/' . $version;

  $js = array(
    $path . '/js/perfect-scrollbar.jquery.' . $js_extension => array(
      'external' => $cdn,
    'scope' => 'footer',
    )
  );
  $css = array(
    $path . '/css/perfect-scrollbar.' . $css_extension => array(
      'external' => $cdn,
    'type' => 'file',
      'media' => 'screen',
    )
  );

  $libraries['perfect_scrollbar'] = array(
    'title' => 'anythingslider',
    'version' => $version,
    'website' => 'https://noraesae.github.io/perfect-scrollbar',
    'js' => $js,
    'css' => $css,
  );
  return $libraries;
}

/*
 * Perfoms check with perfect scrollbar settings and sets up JS by passing required values.
 */
function _set_perfect_scrollbar_settings() {
  $js_array = array();
  $final_array = array();
  $settings = variable_get('perfect_scrollbar_settings', '{class:prefect_scroll|height:400|width:300},{id:prefect_scroll|height:400|width:300}');
  $scrollbar_attributes = explode(',', $settings);
  $counter = 0;
  foreach($scrollbar_attributes as  $attributes) {
    $scroll_attribute = explode('|', rtrim(ltrim($attributes,'{'),'}'));
    foreach($scroll_attribute as $v) {
      $value = explode(':', $v);
      $scroll_attributes[$counter][$value[0]] = $value[1];
      ($value[0] == 'class')? $classes[] = $value[1] : (($value[0] == 'id')? $id[] = $value[1] : 1);
    }
    $counter++;
  }
  drupal_add_js(array('perfect_scrollbar_classes' => $classes), 'setting');
  drupal_add_js(array('perfect_scrollbar_ids' => $id), 'setting');
  drupal_add_js(array('perfect_scrollbar' => $scroll_attributes), 'setting');
  return;
}


