<?php
define('PERFECT_SCROLLBAR_DEFAULT_VERSION', '0.6.16');
define('PERFECT_SCROLLBAR_CDN_URL', 'https://cdnjs.cloudflare.com/ajax/libs/jquery.perfect-scrollbar');

/**
 * @file
 * Perfect Srollbar integration implementation.
 */


/**
 * Implements hook_help().
 */
function perfect_scrollbar_help($path, $arg) {
  switch ($path) {
    // Help for the Perfect Scrollbar module.
    case 'admin/help#perfect_scrollbar':
      $output = '<p>' . t('The Perfect Scrollbar helps content managers, authors to add scroll to their content easily');
      $output .= t('For configuration options see the perfect scrollbar <a href="@config">options & settings page</a>.', array('@config' => url('admin/config/user-interface/perfect_scrollbar'))) . '</p>';
      return $output;
  }
}

/**
 * Implements hook_menu().
 */
function perfect_scrollbar_menu() {
  $items['admin/config/user-interface/perfect_scrollbar'] = array(
    'title' => 'Perfect Scrollbar',
    'description' => 'Perfect Scrollbar configuration in Drupal.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('perfect_scrollbar_configurations'),
    'access arguments' => array('administer perfect scrollbar'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'perfect_scrollbar.admin.inc'
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function perfect_scrollbar_permission() {
  return array(
    'administer perfect scrollbar' => array(
      'title' => t('Administer Perfect scrollbar Options & Settings'),
      'description' => t('Allows a user to configure and apply perfect Scrollbar to content.'),
    ),
  );
}

/*
 *
 *
 */
function perfect_scrollbar_init() {
  if(variable_get('perfect_scrollbar')) {
    drupal_add_js(drupal_get_path('module', 'perfect_scrollbar') .'/js/perfect-scrollbar.min.js', 'file');
    drupal_add_js(drupal_get_path('module', 'perfect_scrollbar') .'/js/add_perfect_scrollbar.js', 'file');
    drupal_add_css(drupal_get_path('module', 'perfect_scrollbar') .'/css/perfect-scrollbar.min.css');

    //Get scrollbar settings
    _set_perfect_scrollbar_settings();
  }
}

/*
 * Perfoms check with perfect scrollbar settings and sets up JS by passing required values.
 */
function _set_perfect_scrollbar_settings() {
  $js_array = array();
  $final_array = array();
  $settings = variable_get('perfect_scrollbar_settings', '{class:prefect_scroll|height:400|width:300},{id:prefect_scroll|height:400|width:300}');
  $scrollbar_attributes = explode(',', $settings);
  $counter = 0;
  foreach($scrollbar_attributes as  $attributes) {
    $scroll_attribute = explode('|', rtrim(ltrim($attributes,'{'),'}'));
    foreach($scroll_attribute as $v) {
      $value = explode(':', $v);
      $scroll_attributes[$counter][$value[0]] = $value[1];
      ($value[0] == 'class')? $classes[] = $value[1] : (($value[0] == 'id')? $id[] = $value[1] : 1);
    }
    $counter++;
  }
  drupal_add_js(array('perfect_scrollbar_classes' => $classes), 'setting');
  drupal_add_js(array('perfect_scrollbar_ids' => $id), 'setting');
  drupal_add_js(array('perfect_scrollbar' => $scroll_attributes), 'setting');
  return;
}


